name: Zephyrus
main: net.lordsofcode.zephyrus.ZephyrusPlugin
version: ${buildVersion}
author: minnymin3
commands:
   levelup:
      description: Levels up the specified player
   levelupitem:
      description: Levels up the item in your hand
   cast:
      description: Casts the specified spell if the caster knows it
   mana:
      description: Displays your mana
   bind:
      description: Binds a spell to a wand
   spelltome:
      description: Gives you the spelltome of the designated spell
   level:
      description: Shows your level progress
   unbind:
      description: Allows you to unbind the spell from the wand
   effects:
      description: Allows you to see which effects are currently active
permissions:
   zephyrus.bind:
      default: true
      description: Allows access to the /bind command.
   zephyrus.cast:
      default: true
      description: Allows access to the /cast command.
   zephyrus.mana:
      default: true
      description: Allows access to the /mana command.
   zephyrus.level:
      default: true
      description: Allows access to the /level command.
   zephyrus.levelup:
      default: op
      description: Allows access to the /levelup command.
   zephyrus.levelup.item:
      default: op
      description: Allows access to the /levelupitem command.
   zephyrus.mana.other:
      default: op
      description: Allows access to the /mana [player] command.
   zephyrus.mana.restore:
      default: op
      description: Allows access to the /mana restore command.
   zephyrus.level.other:
      default: op
      description: Allows access to the /level [player] command.
   zephyrus.buy:
      default: true
      description: Allows the player to buy spells from signs.
   zephyrus.buy.create:
      default: op
      description: Allows the player to create buyspell signs.
   zephyrus.spelltome:
      default: true
      description: Allows players to learn spells from a spelltome.
   zephyrus.xp:
      default: true
      description: Allows the player to gain XP through spell casting or other means
   zephyrus.regionbypass:
      default: false
      description: Allows the player to bypass the allowspells worldguard flag 
   zephyrus.craft.*:
      default: true
      children:
         zephyrus.craft.blinkpearl: true
         zephyrus.craft.lightninggem: true
         zephyrus.craft.growhoe: true
         zephyrus.craft.mana: true
         zephyrus.craft.firerod: true
         zephyrus.craft.wand.basic: true
         zephyrus.craft.wand.advanced: true
load: STARTUP