name: Zephyrus
main: minny.zephyrus.Zephyrus
version: 0.2.0
commands:
   levelup:
   levelupitem:
   cast:
   mana:
   bind:
   spelltome:
   level:
permissions:
   zephyrus.bind:
      default: true
      description: Allows access to the /bind command.
   zephyrus.cast:
      default: true
      description: Allows access to the /cast command.
   zephyrus.levelup:
      default: op
      description: Allows access to the /levelup command.
   zephyrus.levelup.item:
      default: op
      description: Allows access to the /levelupitem command.
   zephyrus.mana:
      default: true
      description: Allows access to the /mana command.
   zephyrus.mana.other:
      default: op
      description: Allows access to the /mana [player] command.
   zephyrus.craft.*:
      default: true
      children:
         zephyrus.craft.blinkpearl: true
         zephyrus.craft.lightninggem: true
         zephyrus.craft.growhoe: true
         zephyrus.craft.lifesuck: true
         zephyrus.craft.mana: true
         zephyrus.craft.firerod: true
         zephyrus.craft.wand: true
   zephyrus.spell.*:
      default: true
      children:
         zephyrus.spell.armour: true
         zephyrus.spell.blink: true
         zephyrus.spell.bolt: true
         zephyrus.spell.butcher: true
         zephyrus.spell.confuse: true
         zephyrus.spell.dig: true
         zephyrus.spell.enderchest: true
         zephyrus.spell.feed: true
         zephyrus.spell.fireball: true
         zephyrus.spell.frenzy: true
         zephyrus.spell.grow: true
         zephyrus.spell.heal: true
         zephyrus.spell.phase: true
         zephyrus.spell.punch: true
         zephyrus.spell.repair: true
         zephyrus.spell.summon: true
         zephyrus.spell.superheat: true
         zephyrus.spell.vanish: true
load: STARTUP