name: Zephyrus
main: minny.zephyrus.Zephyrus
version: 0.1
commands:
   levelup:
   levelupitem:
   cast:
   mana:
   bind:
   spelltome:
permissions:
   zephyrus.bind:
      default: true
      description: Allows access to the /bind command.
   zephyrus.cast:
      default: true
      description: Allows access to the /cast command.
   zephyrus.levelup:
      default: op
      description: Allows access to the /levelup command.
   zephyrus.levelup.item:
      default: op
      description: Allows access to the /levelupitem command.
   zephyrus.mana:
      default: true
      description: Allows access to the /mana command.
   zephyrus.mana.other:
      default: op
      description: Allows access to the /mana [player] command.
load: STARTUP