name: Zephyrus
main: minny.zephyrus.Zephyrus
version: 1.0.0
author: minnymin3
commands:
   levelup:
   levelupitem:
   cast:
   mana:
   bind:
   spelltome:
   level:
   unbind:
permissions:
   zephyrus.bind:
      default: true
      description: Allows access to the /bind command.
   zephyrus.cast:
      default: true
      description: Allows access to the /cast command.
   zephyrus.mana:
      default: true
      description: Allows access to the /mana command.
   zephyrus.level:
      default: true
      description: Allows access to the /level command.
   zephyrus.levelup:
      default: op
      description: Allows access to the /levelup command.
   zephyrus.levelup.item:
      default: op
      description: Allows access to the /levelupitem command.
   zephyrus.mana.other:
      default: op
      description: Allows access to the /mana [player] command.
   zephyrus.level.other:
      default: op
      description: Allows access to the /level [player] command.
   zephyrus.buy:
      default: true
      description: Allows the player to buy spells from signs.
   zephyrus.buy.create:
      default: op
      description: Allows the player to create buyspell signs.
   zephyrus.craft.*:
      default: false
      children:
         zephyrus.craft.blinkpearl: true
         zephyrus.craft.lightninggem: true
         zephyrus.craft.growhoe: true
         zephyrus.craft.lifesuck: true
         zephyrus.craft.mana: true
         zephyrus.craft.firerod: true
         zephyrus.craft.wand: true
   zephyrus.spell.*:
      default: true
load: STARTUP